stages:
  create_yolo_dataset:
    cmd: python src/create_yolo_dataset.py ${create_yolo_dataset}
    deps:
    - data/pool_data
    - src/create_yolo_dataset.py
    outs:
    - data/yolo_dataset/train
    - data/yolo_dataset/val
  train:
    cmd: yolo settings datasets_dir=data dvc=false && python src/train.py ${train}
    deps:
    - data/yolo_dataset/train
    - data/yolo_dataset/val
    - src/train.py
    metrics:
    - results/train/metrics.json
    plots:
    - results/train/plots/metrics:
        x: step
    - results/train/plots/images
    - results/train/plots/sklearn/confusion_matrix.json:
        template: confusion
        x: actual
        y: predicted
        title: Confusion Matrix
        x_label: True Label
        y_label: Predicted Label
    outs:
    - results/train/artifacts/best.pt:
        type: model
        desc: This is a Computer Vision (CV) model that's segmenting out swimming pools
          from satellite images.
        labels:
        - cv
        - segmentation
        - satellite-images
        - yolo
